apiVersion: apps/v1
kind: Deployment
metadata:
  name: keydb
  namespace: default
spec:
  selector:
    matchLabels:
      app: keydb
  template:
    metadata:
      labels:
        app: keydb
    spec:
      containers:
      - name: keydb
        image: eqalpha/keydb
        resources:
          limits:
            memory: "128Mi"
            cpu: 100m"
        ports:
        - containerPort: 6379
